### ISSUE TITLE
HP - "This is the end" message for anonymous contributors

### ISSUE THREAD

**Issue by rosymond** [CitizenScienceCenter/c3s-lab-client#22]
The message "This is the end" has been appearing to users in the following situations:
- several people have been reporting it yesterady, while contributing to project #104. The project is setup to "allow anonymous contributions". However when anonymous users contribute, they get this message either immediately (first time they try to contribute) or after a few contributions, and can not contribute anymore. See console screenshot below.
- I have personally seen it sever times (including yesterday), for just a split second, when I start contributing to a project, as logged-in contributor. Then I can contribute normally. 
- This seems to happen to different people, using different browsers.
- In any case (even before fixing the bug if possible) the message needs to be changed to something more clear: "All tasks have been analysed. Thank you for contributing!"

<img width="1349" alt="console" src="https://user-images.githubusercontent.com/762935/84987378-4f056b80-b140-11ea-9e91-eb25fb4a3e78.png">

**Comment by ngeorgomanolis** [comment]
1. several people have been reporting it yesterady, while contributing to project #104. The project is setup to "allow anonymous contributions". However when anonymous users contribute, they get this message either immediately (first time they try to contribute) or after a few contributions, and can not contribute anymore. See console screenshot below.

**This is normal. If 10 anonymous users have already contributed to all tasks (task status=completed, redundancy ok ) then that's it. For normal users the procedure is as usual.**

2. I have personally seen it sever times (including yesterday), for just a split second, when I start contributing to a project, as logged-in contributor. Then I can contribute normally. 

**This is something else. A loading spinner should be added there in order to avoid such things.**
 
3. This seems to happen to different people, using different browsers.

**Points to number 2.**

4. In any case (even before fixing the bug if possible) the message needs to be changed to something more clear: "All tasks have been analysed. Thank you for contributing!"

**replaced!**

**Comment by rosymond** [comment]
"This is normal. If 10 anonymous users have already contributed to all tasks (task status=completed, redundancy ok ) then that's it. For normal users the procedure is as usual."

At the time this happened in the O17 project there were still a lot of contributions needed ... Anyway, if you don't see any issue with anonymous contribution on your end, we'll keep an eye on this and see if anybody reports this again.
